#!/usr/bin/env bash
# Regenerates SYSPORT_MARJAN.sql (the manual bootstrap) by concatenating the
# ordered db/init/*.sql files. Docker loads those files directly, so this is
# only for running everything in one go:
#   mysql -u root -p < SYSPORT_MARJAN.sql
set -euo pipefail
cd "$(dirname "$0")/.."

out=SYSPORT_MARJAN.sql
cat > "$out" <<'HEADER'
-- SysPort - MARJAN :: bootstrap script (schema + seed)
-- MySQL 8.4. English status codes, DECIMAL money. No AUTO_INCREMENT: ids are
-- allocated through the `sequences` table and the stored procedures.
-- The child column always references the parent id (PRD 4.1 F1).
-- FK constraints are declared inline so table creation order is self-documenting.
--
-- Generated by db/build-bootstrap.sh from db/init/*.sql.
-- Docker loads those files automatically.
-- Run manually with:  mysql -u root -p < SYSPORT_MARJAN.sql
HEADER

for file in db/init/*.sql; do
  printf '\n\n'
  cat "$file"
done >> "$out"

printf 'Regenerated %s (%s lines)\n' "$out" "$(wc -l < "$out" | tr -d ' ')"
